// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/dusbot/honeypotz/init_"
	"github.com/dusbot/honeypotz/module"
)

// Injectors from wire.go:

func NewApp() *app {
	query := init_.InitQuery()
	ssh := module.NewSSH(query)
	telnet := module.NewTelnet(query)
	mysql := module.NewMysql(query)
	v := ProvideModules(ssh, telnet, mysql)
	appApp := New(v)
	return appApp
}
