// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q             = new(Query)
	SSHAccount    *sSHAccount
	SSHCommand    *sSHCommand
	SSHPermission *sSHPermission
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	SSHAccount = &Q.SSHAccount
	SSHCommand = &Q.SSHCommand
	SSHPermission = &Q.SSHPermission
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:            db,
		SSHAccount:    newSSHAccount(db, opts...),
		SSHCommand:    newSSHCommand(db, opts...),
		SSHPermission: newSSHPermission(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	SSHAccount    sSHAccount
	SSHCommand    sSHCommand
	SSHPermission sSHPermission
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		SSHAccount:    q.SSHAccount.clone(db),
		SSHCommand:    q.SSHCommand.clone(db),
		SSHPermission: q.SSHPermission.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		SSHAccount:    q.SSHAccount.replaceDB(db),
		SSHCommand:    q.SSHCommand.replaceDB(db),
		SSHPermission: q.SSHPermission.replaceDB(db),
	}
}

type queryCtx struct {
	SSHAccount    ISSHAccountDo
	SSHCommand    ISSHCommandDo
	SSHPermission ISSHPermissionDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		SSHAccount:    q.SSHAccount.WithContext(ctx),
		SSHCommand:    q.SSHCommand.WithContext(ctx),
		SSHPermission: q.SSHPermission.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
